Parsing
Sadikk/TP-PCC4 pull request #3
Opened 2018-12-08 15:09 UTC by lpaffi

2018-12-08 15:39 UTC, Sadikk requested changes
+ Ce serait bien d'ajouter un test unitaire. Pour la syntaxe/forme, tu peux regarder la branche "cache" j'en aurais fait un (pas encore push mais bientôt)

+ tests fonctionnels si y en a dans les specs (avec le framework de la prof) (j'ai pas regardé si y en avait spécifiquement pour Request, je le dis de manière générale pour celui là)

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
>    #ifdef MAP
je ne suis pas sur que ce soit nécessaire de tracer les appels à toutes les fonctions, l'utilité du debug à la base étant pour tracer les constructeurs/destructeurs pour aider à la gestion mémoire

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +HttpMethod Request::parseMethod(string unparsedMethod) const {
```suggestion
HttpMethod Request::parseMethod(string methodString) const {
```

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +  if(unparsedMethod == "GET"){
I would rather go for a switch in this case

Also, you should adding all http methods (see : https://developer.mozilla.org/fr/docs/Web/HTTP/M%C3%A9thode) and not only GET/POST/OPTIONS

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +    string unparsedMethod;
```suggestion
    string methodString;
```

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +             std::getline(iss, unparsedMethod, ' ') &&
```suggestion
             std::getline(iss, methodString, ' ') &&
```

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +  std::ostream& operator<<(std::ostream & str, const Request& request){
Maybe follow the same structure as an apache log line ? This way we can reconstruct a log file if necessary, and that also includes all necessary informations

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
>              request.swap(tmp);
```suggestion
            swap(*this, tmp);
```

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
>  void Request::swap(Request& other)
```suggestion
void swap(Request & first, Request & second)
```

2018-12-08 15:39 UTC, Sadikk commented on src/Request/Request.cpp
> +  *this = other;
use std::swap on each member ie. 
```suggestion
  using std::swap;
  
  swap(first.ipAddress, second.ipAddress);
  //etc..
```

2018-12-09 10:24 UTC, lpaffi commented on src/Request/Request.cpp
>    #ifdef MAP
Corrigé

2018-12-09 10:29 UTC, lpaffi commented on src/Request/Request.cpp
> +  if(unparsedMethod == "GET"){
Switch only works with integers. 
https://en.cppreference.com/w/cpp/language/switch
Other methods added.

2018-12-09 10:32 UTC, lpaffi commented on src/Request/Request.cpp
> +HttpMethod Request::parseMethod(string unparsedMethod) const {
I'd rather keep the unparsedMethod if you don't mind it. I think the reading becomes more logical ( you're parsing an unparsed string ). It doesn't change a lot though.

2018-12-09 10:32 UTC, lpaffi commented on src/Request/Request.cpp
> +  std::ostream& operator<<(std::ostream & str, const Request& request){
Done. I just wanted to check each attribute individually.

2018-12-09 10:53 UTC, Sadikk commented on src/Request/Request.cpp
>    #ifdef MAP
(tu peux cliquer sur le bouton "Resolve conversation" pour l'indiquer, plutôt que d'ajouter un commentaire ;) )

2018-12-09 11:35 UTC, closed without merging