Parsing
Sadikk/TP-PCC4 pull request #6
Opened 2018-12-09 11:39 UTC by lpaffi

I've fixed the errors you pointed out for the most part.
I added a unparseMethod() which has the sole purpose of translating an int into a enum Method.

I don't know if you can still see the merge request ( I closed it, sorry :p) but I did not implement the switch you asked because switchs only work with integer.

I did not add unitary tests since they're not in the provided file, but we could create our own if you want.

I ran into a problem that I'm not sure how to solve and I'd like your help : when reading the timestamp, we have an additional info, the +0200. There's no such attribute with the mktime, c_time methods, so I'm not sure how to deal with it.

2018-12-09 13:17 UTC, Sadikk commented
The +0200 corresponds to the timezone. It's the %z parameter in strftime (see here : http://www.cplusplus.com/reference/ctime/strftime/ )

Not sure if you're done or not ... ?

Add me as a reviewer (right sidebar on github) when you're done (and you as an assignee) , will then review your code and you will be able to merge if all is okay

2018-12-09 17:14 UTC, lpaffi commented
Thanks. I was using %Z and not %z!
I think I'm done with this class =)

2018-12-09 17:47 UTC, Sadikk requested changes
small things to fix ; but you can merge afterwise, it's okay 👍

2018-12-09 17:47 UTC, Sadikk commented on src/Request/Request.cpp
> +    break;
no need to break after a return

2018-12-09 17:47 UTC, Sadikk commented on src/Request/Request.cpp
> +    return "GET";
```suggestion
        return "GET";
```

2018-12-09 17:47 UTC, Sadikk commented on src/Request/Request.cpp
> +std::swap(first.ipAddress, second.ipAddress);
indentation

2018-12-09 17:47 UTC, Sadikk commented on src/Request/Request.h
> +    void swap(Request& first, Request& second);
```suggestion
    friend void swap(Request& first, Request& second);
```

2018-12-09 17:47 UTC, Sadikk commented on src/Request/Request.h
>  //
missing doc

2018-12-10 20:38 UTC, lpaffi commented on src/Request/Request.h
> +    void swap(Request& first, Request& second);
Fixed

2018-12-11 07:07 UTC, Sadikk requested changes

2018-12-11 07:07 UTC, Sadikk commented on src/Request/Request.cpp
> +<<<<<<< HEAD
erreur de fusion

2018-12-11 07:07 UTC, Sadikk commented on src/Request/Request.cpp
> +>>>>>>> e3476c8b2ecb0799f8167e93a07fe52c510e8641
erreur de fusion

2018-12-11 18:59 UTC, Sadikk approved these changes

2018-12-11 18:59 UTC, merged